name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: BuildUi with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 6.9.1
        arguments: buildUI
    - name: test with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 6.9.1
        arguments: test
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        gradle-version: 6.9.1
        arguments: build sonarqube --info
